name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/gitbook/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: docs/gitbook/package-lock.json

      - name: Install Dependencies
        run: |
          cd docs/gitbook
          npm install

      - name: Build Documentation
        run: |
          cd docs/gitbook
          npm run docs:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/gitbook/docs/.vuepress/dist
          branch: gh-pages
          clean: true 